### ISSUE TITLE
Facebook Crawlers Works Great On Http But Crashed on Https

### ISSUE THREAD

**Issue by adeelibr** [Producters/express-crawler-snapshots#9]
```
intercepted bot request by [facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)]
 phantomjs pool: starting phantomjs instance 1...
 phantomjs pool: phantomjs instance 1 started
 phantomjs instance 1: opening http://demo-apps.servup.io:8081/card/cc2a219f97ca4a2d8b71343e46d2d635
 phantomjs instance 1: error rendering page [object Object] reject@phantomjs://code/start.js:71:70
_onPageOpenFinished@phantomjs://platform/webpage.js:286:27
     -----------------------------------------------------------------------
     at /home/ubuntu/webapp/node_modules/phridge/lib/Phantom.js:202:24
     at Phantom._send (/home/ubuntu/webapp/node_modules/phridge/lib/Phantom.js:201:12)
     at Page.run (/home/ubuntu/webapp/node_modules/phridge/lib/Page.js:60:25)
     at Instance.renderPage (/home/ubuntu/webapp/node_modules/express-crawler-snapshots/lib/instance.js:119:16)
     at /home/ubuntu/webapp/node_modules/express-crawler-snapshots/index.js:108:34
     at /home/ubuntu/webapp/node_modules/express-crawler-snapshots/lib/pool.js:40:9
     at process._tickDomainCallback (internal/process/next_tick.js:135:7)
 GET /card/cc2a219f97ca4a2d8b71343e46d2d635 500 177.609 ms - 993
 reject@phantomjs://code/start.js:71:70
 _onPageOpenFinished@phantomjs://platform/webpage.js:286:27
     -----------------------------------------------------------------------
     at /home/ubuntu/webapp/node_modules/phridge/lib/Phantom.js:202:24
     at Phantom._send (/home/ubuntu/webapp/node_modules/phridge/lib/Phantom.js:201:12)
     at Page.run (/home/ubuntu/webapp/node_modules/phridge/lib/Page.js:60:25)
     at Instance.renderPage (/home/ubuntu/webapp/node_modules/express-crawler-snapshots/lib/instance.js:119:16)
     at /home/ubuntu/webapp/node_modules/express-crawler-snapshots/index.js:108:34
     at /home/ubuntu/webapp/node_modules/express-crawler-snapshots/lib/pool.js:40:9
     at process._tickDomainCallback (internal/process/next_tick.js:135:7)
 phantomjs instance 1: process exited

```

I have to environments for my app one is my staging environment
http://stag.servup.io:8081/card/c78f8fa4924b490da0455f13b0a873cb

The other is is my demo environment
https://demo-apps.servup.io:8081/card/cc2a219f97ca4a2d8b71343e46d2d635

Facebook crawler works great on the staging environment, But on demo when the crawler crawls the page I get the above error from this plugin, any idea how this can be fixed? If you can give me some hint I can make a pull request and work on the code, I just need some direction.

**Comment by adeelibr** [comment]
Also this is my server.js file

```
const express = require('express');
const ejs     = require('ejs');
const path = require('path');
const http = require('http');
const morgan = require('morgan');
const parser = require('body-parser');
const compression      = require('compression');
const crawlerSnapshots = require('express-crawler-snapshots');

const app = express();

app.use(compression()); 
app.use(morgan('dev'));
app.use(parser.json());
app.use(parser.urlencoded({ extended: false }));

app.set('view engine', 'ejs');
// Point static path to dist
app.use(express.static(path.join(__dirname, 'dist')));

//make sure you include the middleware before route handlers
app.use(crawlerSnapshots(/* {options} */));

const routes = require('./server/routes')
app.use('/', routes);

app.get('*.js', (req, res, next) => {
  req.url = req.url + '.gz';
  res.set('Content-Encoding', 'gzip');
  next();
});

/** Get port from environment and store in Express. */
const port = process.env.PORT || '3000';
app.set('port', port);

/** Create HTTP server. */
const server = http.createServer(app);
/** Listen on provided port, on all network interfaces. */
server.listen(port, () => console.log(`Server Running on http://localhost:${port}/`))

```
